language: python
python:
    - "3.6"
install:
  - python setup.py -q install
  - pip install mongomock pymongo pycodestyle pytest-cov numpy pyemd pymorphy2
script:
  - pytest --cov=tgalice --cov-fail-under=75
  - pycodestyle . --max-line-length 120
